Repository GSG-G13/Aya-Heleena, pull requests merged in 2023-03, with the labels that each got.

#2 project-files
  index.html
  script.js
  style.css
Labels: done

#5 bulid html file
  index.html
Labels: done

#8 js coding
  index.html
  script.js
  style.css
Labels: in progress

#10 update js deleteTask function and add time
  index.html
  script.js
  style.css
Labels: waiting review
